/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>

#include "../Inc/gpio.h"
#include "../Inc/systick.h"

static const Pin_t BlueLED = {GPIOB, 7}; // Pin PB7 -> User LD2
static const Pin_t Button = {GPIOC, 13}; // Pin PC13 <- User B1

#define BLINK_PERIOD 1000 // 1 second

static unsigned int loopCount = 0;

int main(void){

	GPIO_Enable(BlueLED);
	GPIO_Mode(BlueLED, OUTPUT);
	GPIO_Output(BlueLED, LOW);

	GPIO_Enable(Button);
	GPIO_Mode(Button, INPUT);

	StartSysTick();

	printf("Welcome to %c%c%c%d!\n", 67, 69, 71, 0xC40);
	while (1) {
		msDelay(BLINK_PERIOD / 2);
		if (!GPIO_Input(Button))
			GPIO_Output(BlueLED, HIGH);

		msDelay(BLINK_PERIOD / 2);
		GPIO_Output(BlueLED, LOW);

		loopCount++;
		printf("Loop count %u\n", loopCount);

	}
}

